apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-lab
data:
  custom.conf: |
    server {
      listen 80;
      location / {
        return 200 'Hello from ConfigMap!';
      }
    }
